- name: Déployer l'application Node.js sur Kubernetes
  hosts: localhost
  user: root
  tasks:
    - name: Appliquer le déploiement
      shell: shell: KUBECTL_INSECURE_SKIP_TLS_VERIFY=true kubectl apply -f files/deployment.yaml


    - name: Appliquer le service
      shell: kubectl apply -f files/service.yaml
