- name: Déployer l'application Node.js sur Kubernetes
  hosts: localhost
  user: root
  tasks:
    - name: Appliquer le déploiement
      shell: kubectl apply -f files/deployment.yaml --insecure-skip-tls-verify --validate=false


    - name: Appliquer le service
      shell: kubectl apply -f files/service.yaml
