apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js-sample
  template:
    metadata:
      labels:
        app: node-js-sample
    spec:
      containers:
      - name: node-js-sample
        image: admin849/node-js-sample:latest # Remplacez "user" par votre nom d'utilisateur DockerHub
        ports:
        - containerPort: 3000
