apiVersion: v1
kind: Service
metadata:
  name: node-js-sample-service
spec:
  selector:
    app: node-js-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
